import bcrypt from 'bcryptjs'

export const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      title: "Samsung Galaxy A55 5G",
      brand: "Samsung",
      model: "Galaxy A55",
      category: "mobile",
      price: 43500,
      description:
        "Samsung Galaxy A35 5G.The phone comes with a 120 Hz refresh rate 6.60-inch touchscreen display offering a resolution of 2340×1080 pixels (FHD+). It comes with 8GB of RAM. The Samsung Galaxy A35 5G runs Android 14 and is powered by a 5000mAh non-removable battery. The Samsung Galaxy A35 5G supports proprietary fast charging. As far as the cameras are concerned, the Samsung Galaxy A35 5G on the rear packs a triple camera setup featuring a 50-megapixel primary camera; an 8-megapixel camera, and a 5-megapixel camera. It has a single front camera setup for selfies, featuring a 13-megapixel sensor. The Samsung Galaxy A35 5G runs One UI 6 is based on Android 14 and packs 128GB, 256GB of inbuilt storage that can be expanded via microSD card (up to 1000GB). The Samsung Galaxy A35 5G measures 161.70 x 78.00 x 8.20mm (height x width x thickness) and weighs 209.00 grams. It was launched in Awesome Iceblue, Awesome Navy, and Awesome Lilac colors. It features an IP67 rating for dust and water protection. It bears a metal body. Connectivity options on the Samsung Galaxy A35 5G include Wi-Fi, GPS, and USB Type-C. Sensors on the phone include an accelerometer, compass/ magnetometer, gyroscope, proximity sensor, and fingerprint sensor.",
      features: [
        "120 Hz refresh rate",
        "6.60-inch touchscreen display",
        "8GB RAM",
        "128GB Storage",
        "5G",
        "Android 14",
      ],
      images: ["https://i.ibb.co/mDcYMCF/Samsung-Galaxy-A55-5-G.jpg"],
      ratings: 5,
      numReviews: 4,
      countInStock: 3,
      variants: "8GB 128GB",
      isFlashSale: false,
      isFeatured: true,
    },
    {
      title: "Samsung Galaxy A55 5G",
      brand: "Samsung",
      model: "Galaxy A55",
      category: "mobile",
      price: 43500,
      description:
        "Samsung Galaxy A35 5G.The phone comes with a 120 Hz refresh rate 6.60-inch touchscreen display offering a resolution of 2340×1080 pixels (FHD+). It comes with 8GB of RAM. The Samsung Galaxy A35 5G runs Android 14 and is powered by a 5000mAh non-removable battery. The Samsung Galaxy A35 5G supports proprietary fast charging. As far as the cameras are concerned, the Samsung Galaxy A35 5G on the rear packs a triple camera setup featuring a 50-megapixel primary camera; an 8-megapixel camera, and a 5-megapixel camera. It has a single front camera setup for selfies, featuring a 13-megapixel sensor. The Samsung Galaxy A35 5G runs One UI 6 is based on Android 14 and packs 128GB, 256GB of inbuilt storage that can be expanded via microSD card (up to 1000GB). The Samsung Galaxy A35 5G measures 161.70 x 78.00 x 8.20mm (height x width x thickness) and weighs 209.00 grams. It was launched in Awesome Iceblue, Awesome Navy, and Awesome Lilac colors. It features an IP67 rating for dust and water protection. It bears a metal body. Connectivity options on the Samsung Galaxy A35 5G include Wi-Fi, GPS, and USB Type-C. Sensors on the phone include an accelerometer, compass/ magnetometer, gyroscope, proximity sensor, and fingerprint sensor.",
      features: [
        "120 Hz refresh rate",
        "6.60-inch touchscreen display",
        "8GB RAM",
        "128GB Storage",
        "5G",
        "Android 14",
      ],
      images: ["https://i.ibb.co/mDcYMCF/Samsung-Galaxy-A55-5-G.jpg"],
      ratings: 5,
      numReviews: 4,
      countInStock: 3,
      variants: "8GB 128GB",
      isFlashSale: true,
      isFeatured: false,
    },
    {
      title: "Samsung Galaxy A55 5G",
      brand: "Samsung",
      model: "Galaxy A55",
      category: "mobile",
      price: 43500,
      description:
        "Samsung Galaxy A35 5G.The phone comes with a 120 Hz refresh rate 6.60-inch touchscreen display offering a resolution of 2340×1080 pixels (FHD+). It comes with 8GB of RAM. The Samsung Galaxy A35 5G runs Android 14 and is powered by a 5000mAh non-removable battery. The Samsung Galaxy A35 5G supports proprietary fast charging. As far as the cameras are concerned, the Samsung Galaxy A35 5G on the rear packs a triple camera setup featuring a 50-megapixel primary camera; an 8-megapixel camera, and a 5-megapixel camera. It has a single front camera setup for selfies, featuring a 13-megapixel sensor. The Samsung Galaxy A35 5G runs One UI 6 is based on Android 14 and packs 128GB, 256GB of inbuilt storage that can be expanded via microSD card (up to 1000GB). The Samsung Galaxy A35 5G measures 161.70 x 78.00 x 8.20mm (height x width x thickness) and weighs 209.00 grams. It was launched in Awesome Iceblue, Awesome Navy, and Awesome Lilac colors. It features an IP67 rating for dust and water protection. It bears a metal body. Connectivity options on the Samsung Galaxy A35 5G include Wi-Fi, GPS, and USB Type-C. Sensors on the phone include an accelerometer, compass/ magnetometer, gyroscope, proximity sensor, and fingerprint sensor.",
      features: [
        "120 Hz refresh rate",
        "6.60-inch touchscreen display",
        "8GB RAM",
        "128GB Storage",
        "5G",
        "Android 14",
      ],
      images: ["https://i.ibb.co/mDcYMCF/Samsung-Galaxy-A55-5-G.jpg"],
      ratings: 5,
      numReviews: 4,
      countInStock: 3,
      variants: "8GB 128GB",
      isFlashSale: true,
      isFeatured: true,
    },
  ],
};
